# Generated by Django 4.2.6 on 2023-10-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_breed_exerciseneeds_alter_breed_friendliness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='color',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='favoritefood',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='favoritetoy',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='gender',
        ),
    ]
