# Generated by Django 4.2.6 on 2023-10-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_dog_age_dog_color_dog_favoritefood_dog_favoritetoy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='Lastname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
