# Generated by Django 4.2.6 on 2023-10-13 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_remove_dog_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dogs.breed'),
        ),
    ]
